#                               numpy

In [1]:
import numpy as np
np.arange(10000000)

array([      0,       1,       2, ..., 9999997, 9999998, 9999999])

In [2]:
np.arange(-10)

array([], dtype=int64)

In [3]:
type(np)

module

In [4]:
my_arr = np.arange(10)
my_list = list(range(10))
%time for _ in range(10): my_arr2 = my_arr * 2
    

CPU times: user 78 µs, sys: 8 µs, total: 86 µs
Wall time: 93.9 µs


In [5]:
%time for _ in range(10): my_list2 = [x * 2 for x in my_list]

CPU times: user 16 µs, sys: 1 µs, total: 17 µs
Wall time: 20 µs


In [6]:
my_arr2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [7]:
my_list2

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [8]:
my_arr3 = my_arr2 * 2

In [10]:
my_arr3

array([ 0,  4,  8, 12, 16, 20, 24, 28, 32, 36])

In [11]:
list3 = my_list2 * 2

In [12]:
list3

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

在数据量较大时  numpy 性能 比list 更有 10-> 100倍 
在数据量较小时 numpy 性能 偏低  但是两者时间 都很小  µs 所以可忽略
整体比较 numpy 性能更优

# 4.1 Numpy ndarray 多维 数组对象

In [13]:
import numpy as np

In [14]:
data = np.random.randn(2,3) 

In [15]:
data

array([[-0.59473355,  0.5555188 , -0.68346691],
       [-0.2002593 , -1.82464104,  1.34227784]])

In [16]:
data * 10

array([[ -5.94733554,   5.55518796,  -6.83466915],
       [ -2.00259302, -18.24641038,  13.42277836]])

In [17]:
data  * 2

array([[-1.18946711,  1.11103759, -1.36693383],
       [-0.4005186 , -3.64928208,  2.68455567]])

In [18]:
data.shape # 每个数组都有一个shape属性 用来表征数组每一维度的数量

(2, 3)

In [19]:
data.dtype #每一个数组都有一个dtype 属性 用来描述数据类型

dtype('float64')

summary:  ndarray numpy下的多维数组对象 属性 shape dtype ndim

# 4.1.1 生成ndarray

In [4]:
import numpy as np
data1 = [2,5,7,6.6,8,0]

In [5]:
data1

[2, 5, 7, 6.6, 8, 0]

In [6]:
array1 = np.array(data1)

In [7]:
array1

array([2. , 5. , 7. , 6.6, 8. , 0. ])

In [8]:
data2 = [[1,2,3,4],[5,6,7,8]]


In [9]:
data2

[[1, 2, 3, 4], [5, 6, 7, 8]]

In [10]:
array2 = np.array(data2)

In [11]:
array2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [13]:
array1.ndim 

1

In [14]:
array1.shape

(6,)

In [15]:
array1.size

6

In [16]:
array1.dtype

dtype('float64')

In [17]:
array2.ndim

2

In [18]:
array2.shape

(2, 4)

In [19]:
array2.dtype

dtype('int64')

In [20]:
np.zeros(3)

array([0., 0., 0.])

In [22]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [23]:
np.zeros((2,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [25]:
range_cus = range(10)

In [26]:
range_cus

range(0, 10)

In [27]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [32]:
np.ones_like(array2)

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [34]:
np.full((2,3),4)

array([[4, 4, 4],
       [4, 4, 4]])

In [36]:
np.ones((2,3),order='C')

array([[1., 1., 1.],
       [1., 1., 1.]])

In [40]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [41]:
np.eye(2,3)

array([[1., 0., 0.],
       [0., 1., 0.]])

In [42]:
np.eye(2,3,1)

array([[0., 1., 0.],
       [0., 0., 1.]])

In [43]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

    summary:  默认数据类型 float64

# 4.1.2 ndarray 的数据类型

In [44]:
arr1 =  np.array([1,2,3], dtype = np.float64)
arr2 = np.array([4,5,6], dtype = np.int32)

In [45]:
arr1.dtype

dtype('float64')

In [46]:
arr2.dtype

dtype('int32')

a  可以使用 astype 方法现实的转换

In [49]:
arr = np.array([1,2,4],dtype=np.int64)

In [50]:
arr.dtype

dtype('int64')

In [51]:
float_arr = arr.astype(np.float64)

In [52]:
float_arr.dtype

dtype('float64')

In [54]:
num_str_arr  = np.array(['1.2','3','5'], dtype=np.string_)
num_str_arr.astype(np.float)

array([1.2, 3. , 5. ])

# 4.1.3 Numpy 数组算数

In [56]:
arr = np.array([[1,2,3],[5,6,7]])


In [57]:
arr

array([[1, 2, 3],
       [5, 6, 7]])

In [58]:
arr*arr

array([[ 1,  4,  9],
       [25, 36, 49]])

In [59]:
arr + arr

array([[ 2,  4,  6],
       [10, 12, 14]])

In [60]:
arr -arr

array([[0, 0, 0],
       [0, 0, 0]])

In [61]:
1/ arr

array([[1.        , 0.5       , 0.33333333],
       [0.2       , 0.16666667, 0.14285714]])

In [62]:
arr2 = np.array([[-1,4,2],[3,90,3]])
arr2>arr1

array([[False,  True, False],
       [ True,  True, False]])

# 4.1.4 基础索引与切片

In [63]:
arr = np.arange(10)

In [64]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [65]:
arr[4]

4

In [66]:
arr[:]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [67]:
arr[:3]

array([0, 1, 2])

In [68]:
arr[5:]

array([5, 6, 7, 8, 9])

In [70]:
arr[4:6]

array([4, 5])

# 4.1.5 布尔索引 4.1.6 神奇索引


In [24]:
import numpy as np
arr = np.ones((8,4),dtype=int)

In [25]:
arr

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [32]:
for i in range(8):
    arr[i] = i
#     for j in range(4):
#         arr[i][j] = i + j

In [33]:
arr

array([[0, 0, 0, 0],
       [1, 1, 1, 1],
       [2, 2, 2, 2],
       [3, 3, 3, 3],
       [4, 4, 4, 4],
       [5, 5, 5, 5],
       [6, 6, 6, 6],
       [7, 7, 7, 7]])

In [34]:
arr[4]

array([4, 4, 4, 4])

In [35]:
arr[[4,3,5]]

array([[4, 4, 4, 4],
       [3, 3, 3, 3],
       [5, 5, 5, 5]])

In [36]:
arr[[-1,-3,2]]

array([[7, 7, 7, 7],
       [5, 5, 5, 5],
       [2, 2, 2, 2]])

In [37]:
arr = np.arange(32)

In [38]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31])

In [39]:
arr.reshape(4,8)

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [40]:
arr.reshape(8,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [41]:
arr[1]

1

In [46]:
arr = arr.reshape(8,4)

In [47]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [48]:
arr[[2,4,0,2],[0,1,3,2]]

array([ 8, 17,  3, 10])

# 4.1.7 数组转置和换轴

In [56]:
arr = np.random.randn(6,3)

In [57]:
arr

array([[ 0.21153895, -0.42819027, -0.62018581],
       [ 0.87569467,  1.82933969,  0.27937135],
       [-0.41691084,  0.13342542,  0.11520466],
       [ 0.22939145,  1.36738617, -0.96146   ],
       [-1.88867902,  0.72563356, -0.48509776],
       [ 0.72259543,  0.93816336, -1.23843053]])

In [58]:
arr.T

array([[ 0.21153895,  0.87569467, -0.41691084,  0.22939145, -1.88867902,
         0.72259543],
       [-0.42819027,  1.82933969,  0.13342542,  1.36738617,  0.72563356,
         0.93816336],
       [-0.62018581,  0.27937135,  0.11520466, -0.96146   , -0.48509776,
        -1.23843053]])

In [59]:
np.dot(arr.T,arr)

array([[ 5.12727757,  1.07682797, -0.13382051],
       [ 1.07682797,  6.82407246, -2.03654661],
       [-0.13382051, -2.03654661,  3.16938625]])

In [67]:
arr = np.ones((3,5))

In [68]:
arr

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [69]:
for i in range(3):
    for j in range(5):
        arr[i][j] = i + j

In [70]:
arr

array([[0., 1., 2., 3., 4.],
       [1., 2., 3., 4., 5.],
       [2., 3., 4., 5., 6.]])

In [71]:
arr.T

array([[0., 1., 2.],
       [1., 2., 3.],
       [2., 3., 4.],
       [3., 4., 5.],
       [4., 5., 6.]])

In [72]:
np.dot(arr,arr.T)

array([[30., 40., 50.],
       [40., 55., 70.],
       [50., 70., 90.]])

In [74]:
arr =  np.arange(16).reshape(2,2,4)

In [75]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [78]:
arr.transpose(0,1,2)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [79]:
arr.transpose(1,0,2)

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [81]:
arr.transpose(0,2,1)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

In [83]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [84]:
arr.T

array([[[ 0,  8],
        [ 4, 12]],

       [[ 1,  9],
        [ 5, 13]],

       [[ 2, 10],
        [ 6, 14]],

       [[ 3, 11],
        [ 7, 15]]])

In [86]:
arr.T.shape

(4, 2, 2)

In [87]:
arr.shape

(2, 2, 4)

In [88]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [89]:
arr.swapaxes(1,2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

In [98]:
arr.transpose(0,2,1)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

summary : 数据转置 换轴  T transpose  swapaxes