## 5.1 pandas 数据结构介绍

### 5.1.1 Series

Series 是一种一维数组型对象 包含一个值序列 也包含数据标签(索引) 

In [1]:
import pandas as pd
from pandas import Series ,DataFrame

obj = pd.Series([3,-5,3,9])

In [2]:
obj

0    3
1   -5
2    3
3    9
dtype: int64

In [3]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [4]:
obj.values

array([ 3, -5,  3,  9])

In [5]:
obj2 = pd.Series([4,-7,3,1],index=['d','b','a','c'])

In [6]:
obj2

d    4
b   -7
a    3
c    1
dtype: int64

In [7]:
obj[1]

-5

In [8]:
obj2['b']

-7

In [9]:
obj2['b'] = -10

In [10]:
obj2['b']

-10

In [12]:
obj2[['c','a','c']]

c    1
a    3
c    1
dtype: int64

In [13]:
obj2

d     4
b   -10
a     3
c     1
dtype: int64

In [14]:
'd' in obj2

True

In [15]:
'100' in obj2

False

In [16]:
3 in obj2

False

     字典 -> series

In [17]:
dict = {'keya':33,'keyb':55}

In [18]:
dict

{'keya': 33, 'keyb': 55}

In [19]:
oc = pd.Series(dict)

In [20]:
oc

keya    33
keyb    55
dtype: int64

In [21]:
oc['keyc'] = 99.8

In [22]:
oc

keya    33.0
keyb    55.0
keyc    99.8
dtype: float64

In [25]:
oc.values

array([33. , 55. , 99.8])

In [26]:
oc.index

Index(['keya', 'keyb', 'keyc'], dtype='object')

In [32]:
status = ['keya','keyb','c','d']

In [33]:
od = pd.Series(dict,index=status)

In [34]:
od

keya    33.0
keyb    55.0
c        NaN
d        NaN
dtype: float64

In [35]:
pd.isnull(od)

keya    False
keyb    False
c        True
d        True
dtype: bool

In [36]:
pd.notnull(od)

keya     True
keyb     True
c       False
d       False
dtype: bool

In [37]:
od

keya    33.0
keyb    55.0
c        NaN
d        NaN
dtype: float64

In [38]:
od.name = 'od_name'

In [39]:
od

keya    33.0
keyb    55.0
c        NaN
d        NaN
Name: od_name, dtype: float64

In [40]:
od.index.name = 'status'

In [42]:
od

status
keya    33.0
keyb    55.0
c        NaN
d        NaN
Name: od_name, dtype: float64

### 5.1.2 DataFrame

In [50]:
data = {'state':['sa','sb','sc','sd','se','sf'],
        'year':[2001,2002,2003,2004,2005,2006],
        'pop':[1.1,2.2,3.3,4.4,5.5,6.6]
       }

In [51]:
frame = pd.DataFrame(data)

In [52]:
frame

state  year  pop
0    sa  2001  1.1
1    sb  2002  2.2
2    sc  2003  3.3
3    sd  2004  4.4
4    se  2005  5.5
5    sf  2006  6.6

In [53]:
frame.head()

state  year  pop
0    sa  2001  1.1
1    sb  2002  2.2
2    sc  2003  3.3
3    sd  2004  4.4
4    se  2005  5.5

In [54]:
pd.DataFrame(data,columns=['year','state','pop'])

year state  pop
0  2001    sa  1.1
1  2002    sb  2.2
2  2003    sc  3.3
3  2004    sd  4.4
4  2005    se  5.5
5  2006    sf  6.6

In [55]:
frame2 = pd.DataFrame(data,columns=['year','state','pop','debt'], index=['one','two','three','four','five','six'])

In [56]:
frame2

year state  pop debt
one    2001    sa  1.1  NaN
two    2002    sb  2.2  NaN
three  2003    sc  3.3  NaN
four   2004    sd  4.4  NaN
five   2005    se  5.5  NaN
six    2006    sf  6.6  NaN

In [57]:
frame2['year']

one      2001
two      2002
three    2003
four     2004
five     2005
six      2006
Name: year, dtype: int64

In [58]:
frame2.name = 'frame_name'

In [59]:
frame2

year state  pop debt
one    2001    sa  1.1  NaN
two    2002    sb  2.2  NaN
three  2003    sc  3.3  NaN
four   2004    sd  4.4  NaN
five   2005    se  5.5  NaN
six    2006    sf  6.6  NaN

In [61]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [62]:
frame2.loc['three']

year     2003
state      sc
pop       3.3
debt      NaN
Name: three, dtype: object

In [69]:
import numpy as np
frame2['debt'] =  np.arange(6)

In [65]:
frame2

year state  pop  debt
one    2001    sa  1.1     0
two    2002    sb  2.2     1
three  2003    sc  3.3     2
four   2004    sd  4.4     3
five   2005    se  5.5     4
six    2006    sf  6.6     5

In [70]:
del frame2['debt']

In [71]:
frame2

year state  pop
one    2001    sa  1.1
two    2002    sb  2.2
three  2003    sc  3.3
four   2004    sd  4.4
five   2005    se  5.5
six    2006    sf  6.6

In [75]:
frame2['debt'] = np.arange(6);

In [76]:
frame2

year state  pop  debt
one    2001    sa  1.1     0
two    2002    sb  2.2     1
three  2003    sc  3.3     2
four   2004    sd  4.4     3
five   2005    se  5.5     4
six    2006    sf  6.6     5

In [78]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [80]:
pop = { 'nevada':{2001:1.1,2002:2.4},
           'chio':{2000:1.09,2002:4.4}
}

In [81]:
pop

{'nevada': {2001: 1.1, 2002: 2.4}, 'chio': {2000: 1.09, 2002: 4.4}}

In [83]:
fc = pd.DataFrame(pop)

In [84]:
fc

nevada  chio
2000     NaN  1.09
2001     1.1   NaN
2002     2.4  4.40

In [85]:
fc.T

2000  2001  2002
nevada   NaN   1.1   2.4
chio    1.09   NaN   4.4

In [87]:
pd.DataFrame(fc, index=[2001,2002,2003])

nevada  chio
2001     1.1   NaN
2002     2.4   4.4
2003     NaN   NaN

In [91]:
fc['chio'][:-1]

2000    1.09
2001     NaN
Name: chio, dtype: float64

In [92]:
fc

nevada  chio
2000     NaN  1.09
2001     1.1   NaN
2002     2.4  4.40

In [93]:
fc.index.name = 'index_name'


In [94]:
fc

nevada  chio
index_name              
2000           NaN  1.09
2001           1.1   NaN
2002           2.4  4.40

In [95]:
fc.columns.name = 'columns_name'

In [96]:
fc

columns_name  nevada  chio
index_name                
2000             NaN  1.09
2001             1.1   NaN
2002             2.4  4.40

In [98]:
fc.values

array([[ nan, 1.09],
       [1.1 ,  nan],
       [2.4 , 4.4 ]])

In [99]:
fc.index

Int64Index([2000, 2001, 2002], dtype='int64', name='index_name')

### 5.1.3 索引对象