In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
np.random.randn(10)

array([ 1.17751964,  3.74861071, -0.78326162, -0.23520714,  1.46084785,
        1.17792225,  0.01954687,  2.78046056,  0.47610984,  0.02308554])

In [12]:
np.random.random_sample()
#np.random.randint(1,100,[5,5]) #(1,100）

0.7778003544808479

In [25]:
number = 10
number * np.random.random_sample((5,)) 

array([5.89042759, 1.2624891 , 2.08942713, 6.1666132 , 3.17536816])

In [29]:
np.random.randint(-100,100,[5]) #(1,100）

array([ 14,  77,  66, -84,  -7])

In [31]:
s1 = pd.Series(np.random.randint(0,100,[4]),index=['a','c','d','e'] )

In [32]:
s1

a    49
c    88
d    94
e    60
dtype: int64

In [33]:
s2 = pd.Series(np.random.randint(-100,0,[5,]) , index = ['a','c','e','f','g'])

In [34]:
s2

a   -36
c   -75
e   -39
f   -15
g   -57
dtype: int64

In [35]:
s1 + s2

a    13.0
c    13.0
d     NaN
e    21.0
f     NaN
g     NaN
dtype: float64

In [38]:
df1 = pd.DataFrame(np.arange(9.).reshape((3,3)) , columns=list('bcd'), index=list('OTC') )

In [39]:
df1

b    c    d
O  0.0  1.0  2.0
T  3.0  4.0  5.0
C  6.0  7.0  8.0

In [45]:
df2 = pd.DataFrame(np.arange(12.).reshape(4,3), columns=list('bde'),index =list("UOTO")  )

In [46]:
df2

b     d     e
U  0.0   1.0   2.0
O  3.0   4.0   5.0
T  6.0   7.0   8.0
O  9.0  10.0  11.0

In [47]:
df1 + df2

b   c     d   e
C  NaN NaN   NaN NaN
O  3.0 NaN   6.0 NaN
O  9.0 NaN  12.0 NaN
T  9.0 NaN  12.0 NaN
U  NaN NaN   NaN NaN

In [48]:
df1 = pd.DataFrame({'A':[1,2]})
df2 = pd.DataFrame({'B':[2,3]})

In [49]:
df1+ df2

A   B
0 NaN NaN
1 NaN NaN

In [50]:
df1 - df2

A   B
0 NaN NaN
1 NaN NaN

### 5.2.5.1 使用填充值 的算数方法

In [51]:
df1 = pd.DataFrame(np.arange(12).reshape(3,4) , columns = list('abcd'))

In [52]:
df1

a  b   c   d
0  0  1   2   3
1  4  5   6   7
2  8  9  10  11

In [54]:
df2 = pd.DataFrame(np.arange(20).reshape(4,5),columns=list('abcde') )

In [55]:
df2

a   b   c   d   e
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14
3  15  16  17  18  19

In [56]:
df1 + df2 

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0  11.0  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [58]:
df1.add(df2,fill_value = 0)

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0  11.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [59]:
1/ df1

a         b         c         d
0       inf  1.000000  0.500000  0.333333
1  0.250000  0.200000  0.166667  0.142857
2  0.125000  0.111111  0.100000  0.090909

In [61]:
df1.div(1)

a  b   c   d
0  0  1   2   3
1  4  5   6   7
2  8  9  10  11

In [62]:
df1.rdiv(1)

a         b         c         d
0       inf  1.000000  0.500000  0.333333
1  0.250000  0.200000  0.166667  0.142857
2  0.125000  0.111111  0.100000  0.090909

In [64]:
df2

a   b   c   d   e
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14
3  15  16  17  18  19

In [65]:
df1.reindex(columns = df2.columns, fill_value = 1.1)

a  b   c   d    e
0  0  1   2   3  1.1
1  4  5   6   7  1.1
2  8  9  10  11  1.1

### 5.2.5.2 DataFrame 和 Series 间的操作

In [74]:
arra = np.arange(16.).reshape(4,4)

In [75]:
arra

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.],
       [12., 13., 14., 15.]])

In [76]:
arrb = np.arange(4) + 2

In [77]:
arrb

array([2, 3, 4, 5])

In [78]:
arra - arrb

array([[-2., -2., -2., -2.],
       [ 2.,  2.,  2.,  2.],
       [ 6.,  6.,  6.,  6.],
       [10., 10., 10., 10.]])

In [88]:
arrc = np.arange(16).reshape(4,4) + 1
rand = np.random.randint(0,10,[4,4])

In [89]:
arrc

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [90]:
rand

array([[7, 1, 6, 8],
       [5, 8, 1, 4],
       [5, 4, 6, 6],
       [5, 8, 4, 8]])

In [92]:
arrc - rand

array([[-6,  1, -3, -4],
       [ 0, -2,  6,  4],
       [ 4,  6,  5,  6],
       [ 8,  6, 11,  8]])

In [93]:
frame= pd.DataFrame(np.arange(12).reshape(4,3), columns = list('bde') , index = list('UOTO'))

In [94]:
frame

b   d   e
U  0   1   2
O  3   4   5
T  6   7   8
O  9  10  11

In [126]:
series = frame.iloc[0]

In [127]:
series

b    0
d    1
e    2
Name: U, dtype: int64

In [128]:
frame

b   d   e
U  0   1   2
O  3   4   5
T  6   7   8
O  9  10  11

In [129]:
series

b    0
d    1
e    2
Name: U, dtype: int64

In [130]:
frame- series

b  d  e
U  0  0  0
O  3  3  3
T  6  6  6
O  9  9  9